import markdown

def render_markdown_with_toc(markdown_text):
    """
    Renders markdown text to HTML and generates a Table of Contents.
    
    Returns a dictionary containing:
    - 'content': The main HTML content.
    - 'toc': The HTML for the Table of Contents.
    """
    md = markdown.Markdown(extensions=['toc', 'fenced_code', 'tables'])
    content = md.convert(markdown_text)
    
    # The 'toc' attribute is automatically generated by the extension
    toc = getattr(md, 'toc', '')
    
    return {
        'content': content,
        'toc': toc
    }